sudo: required
dist: trusty

language: c

compiler:
  - gcc
python:
  - "3.3"

script: "sudo bash ./scripts/travis-build.sh"

before_install:
  - sudo mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')"
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped
